version: '3.0'

services:
  propertyListing-db:
    image: mysql:8
    ports:
      - '3306:3306'
    container_name: 'propertyListing-db'
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_DATABASE=propertyListing'
      - 'MYSQL_PASSWORD=password'
    volumes:
      - './mysql-storage:/var/lib/mysql'
      - './mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './dump:/docker-entrypoint-initdb.d'

  phpmyadmin:
    image: phpmyadmin
    container_name: 'propertyListing-phpmyadmin'
    restart: always
    ports:
      - '8282:80'
    environment:
      - 'PMA_ARBITRARY=1'
    depends_on:
      - propertyListing-db

  propertyListing:
    image: property-listing:latest
    container_name: 'propertyListing-app'
    build:
      context: .
    ports:
      - '8181:80'
    volumes:
      - './src:/var/www/propertyListing'
      - './apache/default.conf:/etc/apache2/sites-enabled/000-default.conf'
    depends_on:
      - propertyListing-db

